services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - mode: ingress
        target: 5000
        published: 3000
    depends_on:
      - database
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:password@database:5432/postgres
      - PGHOST=database
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGDATABASE=postgres
      - PGPORT=5432
    restart: unless-stopped

  database:
    image: postgres:16
    ports:
      - mode: host
        target: 5432
        published: 5432
    environment:
      - POSTGRES_PASSWORD=password
    restart: unless-stopped
